//Este archivo define la estructura global, en este caso
//la fuente (Geist y Geist Mono) y texto suave (antiliased)

//Cada carpeta (ruta) puede tener su propio layout

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import { Urbanist } from "next/font/google";
import { Toaster } from 'react-hot-toast';

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600"], variable: "--font-poppins" });
const urbanist = Urbanist({ subsets: ["latin"], weight: ["400", "600", "700"], variable: "--font-urbanist" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MindLink",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", //No funciona
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${urbanist.variable} ${inter.variable} antialiased`}
      >
        {children}
        <Toaster /> {/* <- Toast Notifications */}
      </body>
    </html>
  );
}

